
PANDOC=/usr/bin/pandoc
PANDOC_OPTIONS=--smart --standalone
PANDOC_PDF_OPTIONS=-V geometry:margin=1in

# Targets and dependencies
.PHONY: clean homework

clean :
	- $(RM) *_T00215814.pdf

exam1 :
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_PDF_OPTIONS) -o Exam1_T00215814.pdf Exam1_T00215814.md

exam2 :
	$(PANDOC) $(PANDOC_OPTIONS) $(PANDOC_PDF_OPTIONS) -o Exam1_T00215814.pdf Exam1_T00215814.md

